In [1]:
import numpy as np
import torch

In [2]:
def f(x, x0, hyps):
    return np.exp(-.5*np.linalg.norm((x-x0)/hps[1:]))*hps[0]

In [38]:
x = np.array([4,5.5])
x0 = np.array([4.5, 5.7])
hps = np.array([1., 2., 2.])

In [4]:
f(x, x0, hps)

0.874040015387569

In [5]:
x_torch = torch.from_numpy(x.astype(np.float32))

In [6]:
x0_torch = torch.from_numpy(x0.astype(np.float32))

In [7]:
hps_torch = torch.from_numpy(hps.astype(np.float32))
hps_torch.requires_grad = True

In [2]:
x_torch = torch.tensor([4, 5.5], dtype=torch.float32)
x0_torch = torch.tensor([4.4, 5.7], dtype=torch.float32)
hps_torch = torch.tensor([1., 2., 2.], dtype=torch.float32, requires_grad=True)

In [11]:
def f(x, x0, hps):
    return torch.exp(-.5*torch.norm((x-x0)/hps[1:]))*hps[0]

In [12]:
f(x_torch, x0_torch, hps_torch)

tensor(0.8942, grad_fn=<MulBackward0>)

In [13]:
func_res = f(x_torch, x0_torch, hps_torch)

In [14]:
torch.autograd.backward((func_res,))

In [15]:
hps_torch.grad

tensor([0.8942, 0.0400, 0.0100])

In [16]:
hps_torch.grad.zero_();

In [31]:
x_torch = torch.tensor([4.7, 5.5], dtype=torch.float32)
x0_torch = torch.tensor([4.4, 5.7], dtype=torch.float32)
hps_torch = torch.tensor([1., 2., 2.], dtype=torch.float32, requires_grad=True)

In [32]:
f(x_torch, x0_torch, hps_torch)

tensor(0.9138, grad_fn=<MulBackward0>)

In [33]:
func_res = f(x_torch, x0_torch, hps_torch)

In [34]:
torch.autograd.backward((func_res,))

In [35]:
hps_torch.grad

tensor([0.9138, 0.0285, 0.0127])

In [36]:
hps_torch.grad.zero_();

In [37]:
hps_torch.grad

tensor([0., 0., 0.])

In [39]:
x = np.array([4,5.5])
x0 = np.array([4.5, 5.7])
hps = np.array([1., 2., 2.])

In [40]:
def f(x, x0, hyps):
    return np.exp(-.5*np.linalg.norm((x-x0)/hps[1:]))*hps[0]

In [43]:
x_torch = torch.from_numpy(x)
x0_torch = torch.from_numpy(x0)
hps_torch = torch.from_numpy(hps)
hps_torch.requires_grad = True

In [50]:
f(x_torch, x0_torch, hps_torch)

0.874040015387569

In [45]:
res

0.874040015387569

In [53]:
class kernel_torch(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        r = x.sum()
        ctx.save_for_backward(r)
        return r
    @staticmethod
    def backward(ctx, grad_output):
        r, = ctx.saved_tensors
        return grad_output*r

In [62]:
r = kernel_torch.apply(torch.ones(2, requires_grad=True))

In [63]:
r

tensor(2., grad_fn=<kernel_torchBackward>)

In [65]:
torch.autograd.backward((r,))

RuntimeError: Function kernel_torchBackward returned an invalid gradient at index 0 - got [] but expected shape compatible with [2] (validate_outputs at /opt/conda/conda-bld/pytorch_1587428266983/work/torch/csrc/autograd/engine.cpp:472)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x4e (0x7f3a15d23b5e in /home/elliott/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x2ae3134 (0x7f3a435f8134 in /home/elliott/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #2: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x548 (0x7f3a435f9368 in /home/elliott/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #3: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7f3a435fb2f2 in /home/elliott/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::Engine::thread_init(int) + 0x39 (0x7f3a435f3969 in /home/elliott/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7f3a4693a558 in /home/elliott/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0xc819d (0x7f3a8561b19d in /home/elliott/anaconda3/lib/python3.7/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6)
frame #7: <unknown function> + 0x76db (0x7f3a8a0a06db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x3f (0x7f3a89dc988f in /lib/x86_64-linux-gnu/libc.so.6)
